apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-postgres
  namespace: iranvault-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-postgres
  template:
    metadata:
      labels:
        app: wallet-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: wallet
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: iranvault-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iranvault-secrets
              key: DB_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: wallet-postgres-pvc