apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matching-engine
  namespace: iranvault-prod
spec:
  serviceName: matching-engine
  replicas: 1
  selector:
    matchLabels:
      app: matching-engine
  template:
    metadata:
      labels:
        app: matching-engine
    spec:
      containers:
      - name: matching-engine
        image: ghcr.io/mb6226/iranvault-matching-engine:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: ENGINE_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SYMBOLS
          value: "BTC-USDT,ETH-USDT"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"