resources:
- ../../base
- ../../infra/postgres
- ../../infra/nats
- ../../auth-service
- ../../wallet-service
- ../../order-service
- ../../matching-engine
- ../../api-gateway
- ../../frontend
- ingress.yaml