apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "market-data.fullname" . }}
  labels:
    {{- include "market-data.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}