apiVersion: v1
kind: ConfigMap
metadata:
  name: iranvault-config
  namespace: iranvault-prod
data:
  NODE_ENV: production
  PORT: "3000"
  LOG_LEVEL: info
  JWT_EXPIRES_IN: 15m
  REFRESH_TOKEN_EXPIRES_IN: 7d
  AUTH_SERVICE_URL: http://auth-service.iranvault-prod.svc.cluster.local
  WALLET_SERVICE_URL: http://wallet-service.iranvault-prod.svc.cluster.local
  ORDER_SERVICE_URL: http://order-service.iranvault-prod.svc.cluster.local
  MATCHING_ENGINE_URL: http://matching-engine.iranvault-prod.svc.cluster.local
  NATS_URL: nats://nats:4222
  REDIS_URL: redis://redis:6379
  DATABASE_URL: postgresql://$(DB_USER):$(DB_PASSWORD)@wallet-postgres.iranvault-prod.svc.cluster.local:5432/wallet