apiVersion: v1
kind: Secret
metadata:
  name: iranvault-secrets
  namespace: iranvault-prod
type: Opaque
stringData:
  JWT_SECRET: change_me_now
  DB_USER: wallet_user
  DB_PASSWORD: strong_wallet_password